=== LokiCheckout/LokiCheckout_Core/etc/loki_checkout.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="config">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="themes" type="lokiCheckoutThemesType" minOccurs="0" />
        <xs:element name="grid_layouts" type="lokiCheckoutGridLayoutsType" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="lokiCheckoutThemesType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="theme" type="lokiCheckoutThemeType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="lokiCheckoutThemeType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="steps" type="lokiCheckoutStepsType"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="label" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="lokiCheckoutStepsType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="step" type="lokiCheckoutStepType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="lokiCheckoutStepType">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="blockName" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="lokiCheckoutGridLayoutsType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="grid_layout" type="lokiCheckoutGridLayoutType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="lokiCheckoutGridLayoutType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="grid" type="lokiCheckoutGridType"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="label" type="xs:string" use="optional"/>
    <xs:attribute name="defaultSortOrder" type="xs:int" use="optional"/>
    <xs:attribute name="defaultColSpan" type="xs:int" use="optional"/>
    <xs:attribute name="defaultMdColSpan" type="xs:int" use="optional"/>
  </xs:complexType>

  <xs:complexType name="lokiCheckoutGridType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="block" type="lokiCheckoutBlockType"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="countryId" type="xs:string" use="optional"/>
    <xs:attribute name="parent" type="xs:string" use="optional"/>
    <xs:attribute name="defaultSortOrder" type="xs:int" use="optional"/>
    <xs:attribute name="defaultColSpan" type="xs:int" use="optional"/>
    <xs:attribute name="defaultMdColSpan" type="xs:int" use="optional"/>
  </xs:complexType>

  <xs:complexType name="lokiCheckoutBlockType">
    <xs:attribute name="alias" type="xs:string" use="required"/>
    <xs:attribute name="sortOrder" type="xs:int" use="optional"/>
    <xs:attribute name="colSpan" type="xs:int" use="optional"/>
    <xs:attribute name="mdColSpan" type="xs:int" use="optional"/>
    <!-- @todo Limit colSpan between 1 and 12 -->
  </xs:complexType>

  <!-- @todo Why can't we just re-use this from config.xsd? -->
  <xs:simpleType name="phpClassName">
    <xs:annotation>
      <xs:documentation>
        A string that matches a Fully Qualified Class Name from PHP, especially not starting
        with a backslash as this is an invalid character to start a class name with but a
        somewhat common mistake so this simple type can be used to validate against it
        already
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="(\\?[a-zA-Z_&#x7f;-&#xff;][a-zA-Z0-9_&#x7f;-&#xff;]*)(\\[a-zA-Z_&#x7f;-&#xff;][a-zA-Z0-9_&#x7f;-&#xff;]*)*"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== LokiCheckout/LokiCheckout_Core/etc/loki_checkout.xml
<?xml version="1.0" encoding="UTF-8" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:LokiCheckout_Core:etc/loki_checkout.xsd">
    <themes>
        <theme name="default" label="Multi Step Checkout (default)">
            <steps>
                <step name="shipping" blockName="loki-checkout.steps.shipping"/>
                <step name="billing" blockName="loki-checkout.steps.billing"/>
            </steps>
        </theme>

        <theme name="onestep" label="One Step Checkout">
            <steps>
                <step name="one" blockName="loki-checkout.steps.one"/>
            </steps>
        </theme>
    </themes>

    <grid_layouts>
        <grid_layout name="default_grid" label="Default grid" defaultColSpan="12" defaultMdColSpan="6">
            <grid name="default">
                <block alias="prefix" sortOrder="10" />
                <block alias="firstname" sortOrder="20" />
                <block alias="middlename" sortOrder="30" />
                <block alias="lastname" sortOrder="40" />
                <block alias="street0" sortOrder="50" />
                <block alias="street1" sortOrder="60" />
                <block alias="street2" sortOrder="70" />
                <block alias="street3" sortOrder="80" />
                <block alias="postcode" sortOrder="90" />
                <block alias="city" sortOrder="100" />
                <block alias="region" sortOrder="110" />
                <block alias="country_id" sortOrder="120" />
                <block alias="telephone" sortOrder="130" />
                <block alias="fax" sortOrder="140" />
                <block alias="company" sortOrder="150" />
                <block alias="vat_id" sortOrder="160" />
            </grid>
        </grid_layout>
    </grid_layouts>
</config>
